[options]
logfile = /var/log/odoo/odoo.log
log_level = info
db_host = db
db_port = 5432
db_user = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons, /mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$VMrZe.89Z0xJKWWs9d67Nw$jh7gVMhKflx/eqq24oBw4DW1f01iIvrzp3oX3oSWi/bZ/nXSDDViCVnlzp6mcEe6N7UtzYvUmsD8Fokic.eh1Q

